name: flutter_result_apps_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  file_picker: ^10.3.2
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: assets/images/logo.png
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/images/logo.png
  macos:
    generate: true
    image_path: assets/images/logo.png
  windows:
    generate: true
    image_path: assets/images/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/